apiVersion: v1
kind: ConfigMap
metadata:
  name: tts-config
data:
  APP_ENV: "dev"
  MP3_BUCKET: "tts-dev"
  REDIS_URL: "redis://redis:6379/0"
  API_BASE_URL: "http://api:8000"
  S3_ENDPOINT: "http://minio:9000"
  S3_REGION: "us-east-1"
