apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tts

resources:
  - ../../base
  - ingress-api.yaml
  - ingress-web.yaml
  - pdb-api.yaml
  - pdb-web.yaml

patchesStrategicMerge:
  - patch-images.yaml
  - patch-replicas.yaml
